version: '3.1'
services:

    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        volumes:
          - ./mongo.data:/data/db
        networks:
            default:
                ipv4_address: 172.1.0.2

    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        networks:
            default:
                ipv4_address: 172.1.0.3

    application:
        build:
            context: ./application
            dockerfile: Dockerfile
        image: node
        container_name: application
        ports:
            - 3000:3000
            - 9000:9000
        dns:
            - 8.8.8.8
            - 1.1.1.1
        volumes:
            - ./application:/var/node
        depends_on:
            - redis
            - mongodb
        links:
            - redis
            - mongodb
        networks:
            default:
                ipv4_address: 172.1.0.4

volumes:
    mysql-data:
        driver: local

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.1.0.0/16